### ISSUE TITLE
Handle multiple NuGet package sources

### ISSUE THREAD

**Issue by ScottLilly** [ScottLilly/Pinax#78]
Read list of sources from %APPDATA%\NuGet\NuGet.config (need to find location for Linux computers)

**Comment by gbowne1** [comment]
This file is in these locations on Linux depending on the installation:

 ~/.config/NuGet/NuGet.Config
 ~/.nuget/NuGet/NuGet.Config
 ~/.config/NuGet/config/NuGet.config 
 ~/.nuget/config/NuGet.config

**Comment by ScottLilly** [comment]
Thanks! I ran Pinax on some of my current client's code and noticed I wasn't able to pick up things in their private NuGet source

**Comment by gbowne1** [comment]
I primarily do .NET stuff in the CLI on Linux so if you need those resources I can provide them.   There are some other possibilities depending on installation (WSL, WSL2, etc. but.. those 4 should cover it. but these locations are also managed sources to NuGet stuff:

    ~/.local/share/NuGet/Cache
    ~/.nuget/packages

**Comment by ScottLilly** [comment]
I checked in changes that "should" read the NuGet.config and read multiple sources. I don't have that setup locally, so will test Monday with my client.

@gbowne1 If you have an environment with multiple NuGet sources, can you please test these changes (especially if you have this in a Linux environment). It's using "Environment.SpecialFolder.ApplicationData", and I hope that handles the different folder locations for Windows/Linux/Mac.

If this is good, I will probably release this as version 1.1 and do some much-needed refactoring before starting work on 1.2

**Comment by gbowne1** [comment]
Sory I missed this, Scott.  Yeah I am goin to do some testing with this in Linux as well since that's my main environment. There's been some minor issues, but I still need to see if it's me, Pinax or something else I'm doing, otherwise it's been fine.  

I do have several customers with multiple NuGet sources and I still need to do more testing.  Same though, this is working pretty well for what I have needed.  I have some clients/customers that just don't update much.  I've been looking for som

**Comment by ScottLilly** [comment]
I think this needs some more work. I still have the outstanding issue to handle security. I mostly checked this change in since it didn't seem to be hurting anything - even if it doesn't fix everything. I need to re-think the purpose of the program, now that I've been using it a bit.
